# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-04 14:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import risks.models.user


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0028_auto_20180606_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='RdhUser',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.Profile')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('people.profile',),
            managers=[
                ('objects', risks.models.user.RdhUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RdhGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=30)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'risks_region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.AddField(
            model_name='rdhgroup',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_in_region', to='risks.Region'),
        ),
        migrations.AddField(
            model_name='rdhgroup',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rdhuser',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_in_region', to='risks.Region'),
        ),
    ]
