# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import risks.models.entity


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('indicator_type', models.CharField(max_length=50)),
                ('unit_of_measure', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'risks_administrative_data',
            },
            bases=(risks.models.entity.LocationAware, models.Model),
        ),
        migrations.CreateModel(
            name='AdministrativeDataValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dimension', models.CharField(db_index=True, max_length=50)),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
                ('adm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_association', to='risks.AdministrativeDivision')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrativedivision_association', to='risks.AdministrativeData')),
            ],
            options={
                'db_table': 'risks_administrative_data_value',
            },
        ),
        migrations.CreateModel(
            name='DymensionInfoFurtherResourceAssociation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('damage_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='risks.DamageAssessment')),
                ('dimension_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.DamageType')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='risks.Region')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.FurtherResource')),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[(b'fiexd_asset', b'fixed_asset'), (b'non_fixed_asset', b'non_fixed_asset'), (b'people', b'people'), (b'damage', b'damage')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('lat', 'lon', 'administrative_division')]),
        ),
    ]
