# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_auto_20181121_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'risks_data_provider',
            },
        ),
        migrations.CreateModel(
            name='DataProviderMappings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_value', models.CharField(max_length=80)),
                ('rdh_value', models.CharField(max_length=80)),
                ('data_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.DataProvider')),
            ],
            options={
                'db_table': 'risks_data_provider_mappings',
                'verbose_name': 'DataProviderMappings',
                'verbose_name_plural': 'DataProviderMappings',
            },
        ),
        migrations.AlterModelOptions(
            name='administrativedivision',
            options={'ordering': ['code', 'name'], 'verbose_name_plural': 'Administrative Divisions'},
        ),
        migrations.AlterModelOptions(
            name='hazard',
            options={'ordering': ['order', 'mnemonic'], 'verbose_name_plural': 'Hazards'},
        ),
        migrations.AddField(
            model_name='hazard',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='risks.RiskApp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hazard',
            name='fa_class',
            field=models.CharField(default=b'fa-times', max_length=64),
        ),
        migrations.AddField(
            model_name='hazard',
            name='state',
            field=models.CharField(choices=[(b'queued', b'Queued'), (b'processing', b'Processing'), (b'ready', b'Ready'), (b'error', b'Error'), (b'draft', b'Draft')], default=b'ready', max_length=64),
        ),
        migrations.AlterModelTable(
            name='administrativedivision',
            table='risks_administrativedivision',
        ),
        migrations.AlterModelTable(
            name='hazard',
            table='risks_hazard',
        ),
    ]
