# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-04 14:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import risks.models.entity
import risks.models.risk_app


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_auto_20190104_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[(b'asset', b'asset'), (b'event', b'event')], default=b'asset', max_length=20)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AssetAttributeValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.Asset')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.EavAttribute')),
            ],
        ),
        migrations.CreateModel(
            name='AssetAttributeValueDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_type', models.CharField(default=b'date', max_length=25)),
                ('value', models.DateField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.Asset')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.EavAttribute')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetAttributeValueDecimal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_type', models.CharField(default=b'decimal', max_length=25)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.Asset')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.EavAttribute')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetAttributeValueInt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_type', models.CharField(default=b'int', max_length=25)),
                ('value', models.IntegerField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.Asset')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.EavAttribute')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetAttributeValueText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_type', models.CharField(default=b'text', max_length=25)),
                ('value', models.TextField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.Asset')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.EavAttribute')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetAttributeValueVarchar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_type', models.CharField(default=b'varchar', max_length=25)),
                ('value', models.CharField(max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.Asset')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.EavAttribute')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Asset categories',
            },
        ),
        migrations.CreateModel(
            name='AssetItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('attributes', models.ManyToManyField(to='risks.EavAttribute')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('state', models.CharField(choices=[(b'queued', b'Queued'), (b'processing', b'Processing'), (b'ready', b'Ready'), (b'error', b'Error'), (b'draft', b'Draft')], default=b'ready', max_length=64)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[(b'asset', b'asset'), (b'event', b'event')], default=b'event', max_length=20)),
                ('code', models.CharField(blank=True, db_index=True, max_length=25, null=True)),
                ('year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('begin_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('attribute_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.AttributeSet')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='risks.AdministrativeDivision')),
                ('hazard_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='risks.Hazard')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='risks.Region')),
            ],
            options={
                'db_table': 'risks_event',
            },
            bases=(risks.models.risk_app.RiskAppAware, risks.models.entity.LocationAware, risks.models.entity.HazardTypeAware, risks.models.entity.Exportable, models.Model),
        ),
        migrations.CreateModel(
            name='EventImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(max_length=255, upload_to=b'data_files')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.Region')),
                ('riskapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.RiskApp')),
            ],
            options={
                'ordering': ['riskapp', 'region'],
                'db_table': 'risks_data_event_files',
                'verbose_name': 'Events: Import Data (Main) from XLSX file',
                'verbose_name_plural': 'Events: Import Data (Main) from XLSX file',
            },
        ),
        migrations.CreateModel(
            name='EventImportDamage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(max_length=255, upload_to=b'data_files')),
                ('allow_null_values', models.BooleanField(default=False)),
                ('adm_level_precision', models.CharField(choices=[(b'1', b'Country'), (b'2', b'Nuts3')], default=b'1', max_length=10)),
                ('damage_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.DamageAssessment')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.Region')),
                ('riskapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.RiskApp')),
            ],
            options={
                'ordering': ['riskapp', 'region', 'damage_assessment', 'adm_level_precision'],
                'db_table': 'risks_event_damage_files',
                'verbose_name': 'Damage Assessment: Import Events Data (Attributes) from XLSX file',
                'verbose_name_plural': 'Damage Assessment: Import Events Data (Atributes) from XLSX file',
            },
        ),
        migrations.CreateModel(
            name='MarketValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_code', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.AssetItem')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Phenomenon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('administrative_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.AdministrativeDivision')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.Event')),
            ],
            options={
                'verbose_name_plural': 'Phenomena',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='attribute_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.AttributeSet'),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.AssetCategory'),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.Location'),
        ),
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.Owner'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=django.contrib.postgres.indexes.GinIndex(fields=[b'details'], name=b'event_detail_gin'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=django.contrib.postgres.indexes.GinIndex(fields=[b'details'], name=b'asset_details_gin'),
        ),
    ]
