# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-12 08:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0003_auto_20181121_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventattributevaluedate',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='eventattributevaluedate',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventattributevaluedecimal',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='eventattributevaluedecimal',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventattributevalueint',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='eventattributevalueint',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventattributevaluetext',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='eventattributevaluetext',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventattributevaluevarchar',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='eventattributevaluevarchar',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='riskapp',
            name='name',
            field=models.CharField(choices=[(b'data_extraction', b'Data Extraction'), (b'cost_benefit_analysis', b'Cost Benefit Analysis')], max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name='event',
            index=django.contrib.postgres.indexes.GinIndex(fields=[b'data'], name=b'data_gin'),
        ),
        migrations.DeleteModel(
            name='EventAttributeValueDate',
        ),
        migrations.DeleteModel(
            name='EventAttributeValueDecimal',
        ),
        migrations.DeleteModel(
            name='EventAttributeValueInt',
        ),
        migrations.DeleteModel(
            name='EventAttributeValueText',
        ),
        migrations.DeleteModel(
            name='EventAttributeValueVarchar',
        ),
    ]
