# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-04 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0003_auto_20190104_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'risks_data_provider',
            },
        ),
        migrations.CreateModel(
            name='DataProviderMappings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_value', models.CharField(max_length=80)),
                ('rdh_value', models.CharField(max_length=80)),
                ('data_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.DataProvider')),
            ],
            options={
                'db_table': 'risks_data_provider_mappings',
                'verbose_name': 'DataProviderMappings',
                'verbose_name_plural': 'DataProviderMappings',
            },
        ),
    ]
