# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-04 14:51
from __future__ import unicode_literals

from django.db import migrations


def set_default_attribute_set(apps, schema_editor):
    AttributeSet = apps.get_model('risks', 'AttributeSet')
    attribute_set = AttributeSet.objects.create(name='default')

class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0004_dataprovider_dataprovidermappings'),
    ]

    operations = [
        migrations.RunPython(set_default_attribute_set),
    ]
