# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-07 13:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0005_auto_20190104_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageAssessmentEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entry', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='damageassessment',
            name='values',
        ),
    ]
