# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-07 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0006_auto_20190107_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='damageassessmententry',
            options={'verbose_name_plural': 'Damage Assessment Entries'},
        ),
        migrations.AlterModelTable(
            name='damageassessmententry',
            table='risks_damage_assessment_entry',
        ),
    ]
