# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-12 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0006_auto_20181212_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attribute_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='risks.AttributeSet'),
            preserve_default=False,
        ),
    ]
