# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-08 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0033_auto_20180606_1543'),
        ('risks', '0007_auto_20190107_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='damagetype',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='damageassessment',
            name='additional_layers',
            field=models.ManyToManyField(blank=True, to='layers.Layer'),
        ),
        migrations.AlterModelTable(
            name='damagetype',
            table='risks_damagetype',
        ),
    ]
