# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-09 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0008_auto_20190108_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(max_length=255, upload_to=b'data_files')),
                ('damage_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.DamageAssessment')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.Region')),
                ('riskapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.RiskApp')),
            ],
            options={
                'ordering': ['riskapp', 'region', 'damage_assessment'],
                'db_table': 'risks_event_data_files',
                'verbose_name': 'Damage Assessment: Import Events Data from XLSX file',
                'verbose_name_plural': 'Damage Assessment: Import Events Data from XLSX file',
            },
        ),
        migrations.RemoveField(
            model_name='eventimport',
            name='region',
        ),
        migrations.RemoveField(
            model_name='eventimport',
            name='riskapp',
        ),
        migrations.RemoveField(
            model_name='eventimportdamage',
            name='damage_assessment',
        ),
        migrations.RemoveField(
            model_name='eventimportdamage',
            name='region',
        ),
        migrations.RemoveField(
            model_name='eventimportdamage',
            name='riskapp',
        ),
        migrations.DeleteModel(
            name='EventImport',
        ),
        migrations.DeleteModel(
            name='EventImportDamage',
        ),
    ]
