# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-12 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0008_auto_20181212_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='begin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
