# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 15:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0009_auto_20190109_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
