# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-12 16:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0010_auto_20181212_1318'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name=b'data_gin',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='data',
            new_name='details',
        ),
        migrations.AddField(
            model_name='asset',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=django.contrib.postgres.indexes.GinIndex(fields=[b'details'], name=b'data_gin'),
        ),
    ]
