# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-17 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0010_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='damageassessment',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='damageassessment_association', to='risks.Style'),
        ),
    ]
