# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-23 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0033_auto_20180606_1543'),
        ('risks', '0011_damageassessment_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='related_layers',
            field=models.ManyToManyField(blank=True, to='layers.Layer'),
        ),
    ]
