# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-12 16:28
from __future__ import unicode_literals

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0011_auto_20181212_1607'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='asset',
            name=b'data_gin',
        ),
        migrations.AddIndex(
            model_name='event',
            index=django.contrib.postgres.indexes.GinIndex(fields=[b'details'], name=b'event_detail_gin'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=django.contrib.postgres.indexes.GinIndex(fields=[b'details'], name=b'asset_details_gin'),
        ),
    ]
