# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-28 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0012_event_related_layers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysistype',
            name='scope',
        ),
        migrations.AddField(
            model_name='damageassessment',
            name='scope',
            field=models.CharField(choices=[(b'risk', b'Risk'), (b'event', b'Event')], default=(b'risk', b'Risk'), max_length=25),
        ),
    ]
