# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-01 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0013_auto_20190128_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='damageassessmententry',
            name='phenomenon',
            field=models.ForeignKey(default=79, on_delete=django.db.models.deletion.CASCADE, related_name='damage_assessment_entries', to='risks.Phenomenon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phenomenon',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phenomena', to='risks.Event'),
        ),
    ]
