# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-01 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0014_auto_20190201_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damageassessmententry',
            name='phenomenon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='damage_assessment_entries', to='risks.Phenomenon'),
        ),
    ]
