# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-01 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0015_auto_20190201_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='damageassessmententry',
            name='damage_assessment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='risks.DamageAssessment'),
            preserve_default=False,
        ),
    ]
