# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-06 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0016_damageassessmententry_damage_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprovider',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
