# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-06 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0017_dataprovider_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataprovider',
            name='order',
        ),
        migrations.AddField(
            model_name='dataprovidermappings',
            name='hazard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='data_provider_mappings', to='risks.Hazard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataprovidermappings',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataprovidermappings',
            name='data_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='risks.DataProvider'),
        ),
    ]
