# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-06 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0018_auto_20190206_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataprovidermappings',
            options={'verbose_name': 'Data Provider Mappings', 'verbose_name_plural': 'Data Provider Mappings'},
        ),
        migrations.AlterField(
            model_name='dataprovidermappings',
            name='provider_value',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='dataprovidermappings',
            name='rdh_value',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
